// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/photon_im.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PhotonAck;
@class PhotonAudioMsgData;
@class PhotonAuth;
@class PhotonAuthRet;
@class PhotonBadge;
@class PhotonChannelMsg;
@class PhotonCustomMsg;
@class PhotonDebugLogClear;
@class PhotonDebugLogLevel;
@class PhotonDebugLogPrint;
@class PhotonDebugLogTagAdd;
@class PhotonDebugLogTagClear;
@class PhotonDebugLogUpload;
@class PhotonDelCMsg;
@class PhotonDelGMsg;
@class PhotonDelMsg;
@class PhotonDisconnect;
@class PhotonFileMsgData;
@class PhotonFin;
@class PhotonGMsg;
@class PhotonImStatLogConfig;
@class PhotonImTraceConfig;
@class PhotonImageMsgData;
@class PhotonIndicatorFilter;
@class PhotonJoinRoom;
@class PhotonLocationMsgData;
@class PhotonMsg;
@class PhotonMsgRead;
@class PhotonPeriodicReport;
@class PhotonPingMsg;
@class PhotonPongMsg;
@class PhotonPsh;
@class PhotonQuitRoom;
@class PhotonRawMsgData;
@class PhotonReadCMsg;
@class PhotonRealtimeReport;
@class PhotonRecallCMsg;
@class PhotonRecallGMsg;
@class PhotonRecallMsg;
@class PhotonReplyCEmoji;
@class PhotonRet;
@class PhotonRichTextMsgData;
@class PhotonRoomMsg;
@class PhotonSync;
@class PhotonSyncCHistory;
@class PhotonSyncCMsg;
@class PhotonTextMsgData;
@class PhotonVideoMsgData;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PhotonCoordinateSystem

typedef GPB_ENUM(PhotonCoordinateSystem) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PhotonCoordinateSystem_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PhotonCoordinateSystem_Wgs84 = 0,
  PhotonCoordinateSystem_Gcj02 = 1,
  PhotonCoordinateSystem_Bd09 = 2,
};

GPBEnumDescriptor *PhotonCoordinateSystem_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PhotonCoordinateSystem_IsValidValue(int32_t value);

#pragma mark - Enum PhotonHashAlg

/** hash算法 */
typedef GPB_ENUM(PhotonHashAlg) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PhotonHashAlg_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PhotonHashAlg_None = 0,
  PhotonHashAlg_Md5 = 1,
  PhotonHashAlg_Sha1 = 2,
  PhotonHashAlg_Sha256 = 3,
};

GPBEnumDescriptor *PhotonHashAlg_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PhotonHashAlg_IsValidValue(int32_t value);

#pragma mark - Enum PhotonChannelMsg_AtType

typedef GPB_ENUM(PhotonChannelMsg_AtType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PhotonChannelMsg_AtType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 消息中不包含at */
  PhotonChannelMsg_AtType_AtTypeDefault = 0,

  /** 不是at的所有人 */
  PhotonChannelMsg_AtType_AtTypeNotAll = 1,

  /** at的所有频道成员 */
  PhotonChannelMsg_AtType_AtTypeAll = 2,
};

GPBEnumDescriptor *PhotonChannelMsg_AtType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PhotonChannelMsg_AtType_IsValidValue(int32_t value);

#pragma mark - Enum PhotonGMsg_AtType

typedef GPB_ENUM(PhotonGMsg_AtType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PhotonGMsg_AtType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 消息中不包含at */
  PhotonGMsg_AtType_AtTypeDefault = 0,

  /** 不是at的所有人 */
  PhotonGMsg_AtType_AtTypeNotAll = 1,

  /** at的所有群成员 */
  PhotonGMsg_AtType_AtTypeAll = 2,
};

GPBEnumDescriptor *PhotonGMsg_AtType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PhotonGMsg_AtType_IsValidValue(int32_t value);

#pragma mark - PhotonPhotonImRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PhotonPhotonImRoot : GPBRootObject
@end

#pragma mark - PhotonPBPacket

typedef GPB_ENUM(PhotonPBPacket_FieldNumber) {
  PhotonPBPacket_FieldNumber_Auth = 1,
  PhotonPBPacket_FieldNumber_AuthRet = 2,
  PhotonPBPacket_FieldNumber_Ret = 3,
  PhotonPBPacket_FieldNumber_Disconnect = 4,
  PhotonPBPacket_FieldNumber_Psh = 5,
  PhotonPBPacket_FieldNumber_Sync = 6,
  PhotonPBPacket_FieldNumber_Ack = 7,
  PhotonPBPacket_FieldNumber_Fin = 8,
  PhotonPBPacket_FieldNumber_CustomMsg = 9,
  PhotonPBPacket_FieldNumber_Msg = 10,
  PhotonPBPacket_FieldNumber_Gmsg = 11,
  PhotonPBPacket_FieldNumber_RecallMsg = 12,
  PhotonPBPacket_FieldNumber_RecallGmsg = 13,
  PhotonPBPacket_FieldNumber_MsgRead = 14,
  PhotonPBPacket_FieldNumber_Badge = 15,
  PhotonPBPacket_FieldNumber_DelMsg = 16,
  PhotonPBPacket_FieldNumber_DelGmsg = 17,
  PhotonPBPacket_FieldNumber_RoomMsg = 18,
  PhotonPBPacket_FieldNumber_JoinRoom = 19,
  PhotonPBPacket_FieldNumber_QuitRoom = 20,
  PhotonPBPacket_FieldNumber_Ping = 21,
  PhotonPBPacket_FieldNumber_Pong = 22,
  PhotonPBPacket_FieldNumber_ChannelMsg = 23,
  PhotonPBPacket_FieldNumber_RecallCmsg = 24,
  PhotonPBPacket_FieldNumber_DelCmsg = 25,
  PhotonPBPacket_FieldNumber_SyncCmsg = 26,
  PhotonPBPacket_FieldNumber_ReadCmsg = 27,
  PhotonPBPacket_FieldNumber_SyncChistory = 28,
  PhotonPBPacket_FieldNumber_ReplyCemoji = 29,
  PhotonPBPacket_FieldNumber_DebugLogUpload = 50,
  PhotonPBPacket_FieldNumber_DebugLogClear = 51,
  PhotonPBPacket_FieldNumber_DebugLogTagAdd = 52,
  PhotonPBPacket_FieldNumber_DebugLogTagClear = 53,
  PhotonPBPacket_FieldNumber_DebugLogPrint = 54,
  PhotonPBPacket_FieldNumber_DebugLogLevel = 55,
  PhotonPBPacket_FieldNumber_ImTraceConfig = 56,
  PhotonPBPacket_FieldNumber_ImStatLogConfig = 57,
  PhotonPBPacket_FieldNumber_Lt = 101,
  PhotonPBPacket_FieldNumber_Lv = 102,
};

typedef GPB_ENUM(PhotonPBPacket_Data_OneOfCase) {
  PhotonPBPacket_Data_OneOfCase_GPBUnsetOneOfCase = 0,
  PhotonPBPacket_Data_OneOfCase_Auth = 1,
  PhotonPBPacket_Data_OneOfCase_AuthRet = 2,
  PhotonPBPacket_Data_OneOfCase_Ret = 3,
  PhotonPBPacket_Data_OneOfCase_Disconnect = 4,
  PhotonPBPacket_Data_OneOfCase_Psh = 5,
  PhotonPBPacket_Data_OneOfCase_Sync = 6,
  PhotonPBPacket_Data_OneOfCase_Ack = 7,
  PhotonPBPacket_Data_OneOfCase_Fin = 8,
  PhotonPBPacket_Data_OneOfCase_CustomMsg = 9,
  PhotonPBPacket_Data_OneOfCase_Msg = 10,
  PhotonPBPacket_Data_OneOfCase_Gmsg = 11,
  PhotonPBPacket_Data_OneOfCase_RecallMsg = 12,
  PhotonPBPacket_Data_OneOfCase_RecallGmsg = 13,
  PhotonPBPacket_Data_OneOfCase_MsgRead = 14,
  PhotonPBPacket_Data_OneOfCase_Badge = 15,
  PhotonPBPacket_Data_OneOfCase_DelMsg = 16,
  PhotonPBPacket_Data_OneOfCase_DelGmsg = 17,
  PhotonPBPacket_Data_OneOfCase_RoomMsg = 18,
  PhotonPBPacket_Data_OneOfCase_JoinRoom = 19,
  PhotonPBPacket_Data_OneOfCase_QuitRoom = 20,
  PhotonPBPacket_Data_OneOfCase_Ping = 21,
  PhotonPBPacket_Data_OneOfCase_Pong = 22,
  PhotonPBPacket_Data_OneOfCase_ChannelMsg = 23,
  PhotonPBPacket_Data_OneOfCase_RecallCmsg = 24,
  PhotonPBPacket_Data_OneOfCase_DelCmsg = 25,
  PhotonPBPacket_Data_OneOfCase_SyncCmsg = 26,
  PhotonPBPacket_Data_OneOfCase_ReadCmsg = 27,
  PhotonPBPacket_Data_OneOfCase_SyncChistory = 28,
  PhotonPBPacket_Data_OneOfCase_ReplyCemoji = 29,
  PhotonPBPacket_Data_OneOfCase_DebugLogUpload = 50,
  PhotonPBPacket_Data_OneOfCase_DebugLogClear = 51,
  PhotonPBPacket_Data_OneOfCase_DebugLogTagAdd = 52,
  PhotonPBPacket_Data_OneOfCase_DebugLogTagClear = 53,
  PhotonPBPacket_Data_OneOfCase_DebugLogPrint = 54,
  PhotonPBPacket_Data_OneOfCase_DebugLogLevel = 55,
  PhotonPBPacket_Data_OneOfCase_ImTraceConfig = 56,
  PhotonPBPacket_Data_OneOfCase_ImStatLogConfig = 57,
};

/**
 * [上下行]协议体
 **/
@interface PhotonPBPacket : GPBMessage

/** 非必输 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *lt;

/** 非必输 */
@property(nonatomic, readwrite) int64_t lv;

@property(nonatomic, readonly) PhotonPBPacket_Data_OneOfCase dataOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) PhotonAuth *auth;

@property(nonatomic, readwrite, strong, null_resettable) PhotonAuthRet *authRet;

@property(nonatomic, readwrite, strong, null_resettable) PhotonRet *ret;

@property(nonatomic, readwrite, strong, null_resettable) PhotonDisconnect *disconnect;

@property(nonatomic, readwrite, strong, null_resettable) PhotonPsh *psh;

@property(nonatomic, readwrite, strong, null_resettable) PhotonSync *sync;

@property(nonatomic, readwrite, strong, null_resettable) PhotonAck *ack;

@property(nonatomic, readwrite, strong, null_resettable) PhotonFin *fin;

@property(nonatomic, readwrite, strong, null_resettable) PhotonCustomMsg *customMsg;

@property(nonatomic, readwrite, strong, null_resettable) PhotonMsg *msg;

@property(nonatomic, readwrite, strong, null_resettable) PhotonGMsg *gmsg;

@property(nonatomic, readwrite, strong, null_resettable) PhotonRecallMsg *recallMsg;

@property(nonatomic, readwrite, strong, null_resettable) PhotonRecallGMsg *recallGmsg;

@property(nonatomic, readwrite, strong, null_resettable) PhotonMsgRead *msgRead;

@property(nonatomic, readwrite, strong, null_resettable) PhotonBadge *badge;

@property(nonatomic, readwrite, strong, null_resettable) PhotonDelMsg *delMsg;

@property(nonatomic, readwrite, strong, null_resettable) PhotonDelGMsg *delGmsg;

@property(nonatomic, readwrite, strong, null_resettable) PhotonRoomMsg *roomMsg;

@property(nonatomic, readwrite, strong, null_resettable) PhotonJoinRoom *joinRoom;

@property(nonatomic, readwrite, strong, null_resettable) PhotonQuitRoom *quitRoom;

@property(nonatomic, readwrite, strong, null_resettable) PhotonPingMsg *ping;

@property(nonatomic, readwrite, strong, null_resettable) PhotonPongMsg *pong;

@property(nonatomic, readwrite, strong, null_resettable) PhotonChannelMsg *channelMsg;

@property(nonatomic, readwrite, strong, null_resettable) PhotonRecallCMsg *recallCmsg;

@property(nonatomic, readwrite, strong, null_resettable) PhotonDelCMsg *delCmsg;

@property(nonatomic, readwrite, strong, null_resettable) PhotonSyncCMsg *syncCmsg;

@property(nonatomic, readwrite, strong, null_resettable) PhotonReadCMsg *readCmsg;

@property(nonatomic, readwrite, strong, null_resettable) PhotonSyncCHistory *syncChistory;

@property(nonatomic, readwrite, strong, null_resettable) PhotonReplyCEmoji *replyCemoji;

@property(nonatomic, readwrite, strong, null_resettable) PhotonDebugLogUpload *debugLogUpload;

@property(nonatomic, readwrite, strong, null_resettable) PhotonDebugLogClear *debugLogClear;

@property(nonatomic, readwrite, strong, null_resettable) PhotonDebugLogTagAdd *debugLogTagAdd;

@property(nonatomic, readwrite, strong, null_resettable) PhotonDebugLogTagClear *debugLogTagClear;

@property(nonatomic, readwrite, strong, null_resettable) PhotonDebugLogPrint *debugLogPrint;

@property(nonatomic, readwrite, strong, null_resettable) PhotonDebugLogLevel *debugLogLevel;

@property(nonatomic, readwrite, strong, null_resettable) PhotonImTraceConfig *imTraceConfig;

@property(nonatomic, readwrite, strong, null_resettable) PhotonImStatLogConfig *imStatLogConfig;

@end

/**
 * Clears whatever value was set for the oneof 'data'.
 **/
void PhotonPBPacket_ClearDataOneOfCase(PhotonPBPacket *message);

#pragma mark - PhotonAuth

typedef GPB_ENUM(PhotonAuth_FieldNumber) {
  PhotonAuth_FieldNumber_AppId = 1,
  PhotonAuth_FieldNumber_Token = 2,
  PhotonAuth_FieldNumber_UserId = 3,
  PhotonAuth_FieldNumber_DeviceId = 4,
  PhotonAuth_FieldNumber_ClientType = 5,
  PhotonAuth_FieldNumber_Version = 6,
  PhotonAuth_FieldNumber_Extra = 100,
};

/**
 * [上行]登录鉴权
 **/
@interface PhotonAuth : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientType;

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extra;
/** The number of items in @c extra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extra_Count;

@end

#pragma mark - PhotonAuthRet

typedef GPB_ENUM(PhotonAuthRet_FieldNumber) {
  PhotonAuthRet_FieldNumber_Ec = 1,
  PhotonAuthRet_FieldNumber_Em = 2,
  PhotonAuthRet_FieldNumber_Ap = 3,
  PhotonAuthRet_FieldNumber_Extra = 4,
};

/**
 * [下行]登录鉴权回执
 **/
@interface PhotonAuthRet : GPBMessage

@property(nonatomic, readwrite) int32_t ec;

@property(nonatomic, readwrite, copy, null_resettable) NSString *em;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ap;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extra;
/** The number of items in @c extra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extra_Count;

@end

#pragma mark - PhotonRet

typedef GPB_ENUM(PhotonRet_FieldNumber) {
  PhotonRet_FieldNumber_Id_p = 1,
  PhotonRet_FieldNumber_RetType = 2,
  PhotonRet_FieldNumber_Time = 3,
  PhotonRet_FieldNumber_Ec = 4,
  PhotonRet_FieldNumber_Em = 5,
  PhotonRet_FieldNumber_DataType = 6,
};

/**
 * [下行]（当前业务中只有下行，未来也可支持上行）通用消息回执
 **/
@interface PhotonRet : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int32_t retType;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite) int32_t ec;

@property(nonatomic, readwrite, copy, null_resettable) NSString *em;

@property(nonatomic, readwrite) int32_t dataType;

@end

#pragma mark - PhotonDisconnect

typedef GPB_ENUM(PhotonDisconnect_FieldNumber) {
  PhotonDisconnect_FieldNumber_Ec = 1,
  PhotonDisconnect_FieldNumber_Em = 2,
  PhotonDisconnect_FieldNumber_Ap = 3,
};

/**
 * [下行]被踢下线或重定向到指定ip
 **/
@interface PhotonDisconnect : GPBMessage

@property(nonatomic, readwrite) int32_t ec;

@property(nonatomic, readwrite, copy, null_resettable) NSString *em;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ap;

@end

#pragma mark - PhotonPsh

/**
 * [下行]sync协议，服务端通知客户端开始sync
 **/
@interface PhotonPsh : GPBMessage

@end

#pragma mark - PhotonSync

typedef GPB_ENUM(PhotonSync_FieldNumber) {
  PhotonSync_FieldNumber_Clvs = 1,
};

/**
 * [上行]客户端发起sync
 **/
@interface PhotonSync : GPBMessage

/** 非必输 */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *clvs;
/** The number of items in @c clvs without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger clvs_Count;

@end

#pragma mark - PhotonAck

typedef GPB_ENUM(PhotonAck_FieldNumber) {
  PhotonAck_FieldNumber_Remain = 1,
  PhotonAck_FieldNumber_Lvs = 2,
};

/**
 * [下行]服务端给客户端sync的响应
 **/
@interface PhotonAck : GPBMessage

@property(nonatomic, readwrite) int32_t remain;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *lvs;
/** The number of items in @c lvs without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger lvs_Count;

@end

#pragma mark - PhotonFin

typedef GPB_ENUM(PhotonFin_FieldNumber) {
  PhotonFin_FieldNumber_Lvs = 2,
};

/**
 * [上行]客户端sync结束收到消息处理完成，通知服务端消息处理游标位置
 **/
@interface PhotonFin : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *lvs;
/** The number of items in @c lvs without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger lvs_Count;

@end

#pragma mark - PhotonCustomMsg

typedef GPB_ENUM(PhotonCustomMsg_FieldNumber) {
  PhotonCustomMsg_FieldNumber_Id_p = 1,
  PhotonCustomMsg_FieldNumber_Data_p = 2,
  PhotonCustomMsg_FieldNumber_Time = 3,
  PhotonCustomMsg_FieldNumber_Fr = 4,
  PhotonCustomMsg_FieldNumber_To = 5,
  PhotonCustomMsg_FieldNumber_Extra = 100,
  PhotonCustomMsg_FieldNumber_InterExtra = 101,
};

/**
 * [上下行]自定义消息
 **/
@interface PhotonCustomMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** 业务方自定义数据 */
@property(nonatomic, readwrite, strong, null_resettable) PhotonRawMsgData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extra;
/** The number of items in @c extra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extra_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *interExtra;
/** The number of items in @c interExtra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger interExtra_Count;

@end

#pragma mark - PhotonJoinRoom

typedef GPB_ENUM(PhotonJoinRoom_FieldNumber) {
  PhotonJoinRoom_FieldNumber_Id_p = 1,
  PhotonJoinRoom_FieldNumber_RoomId = 2,
  PhotonJoinRoom_FieldNumber_Time = 3,
};

@interface PhotonJoinRoom : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;

@property(nonatomic, readwrite) int64_t time;

@end

#pragma mark - PhotonQuitRoom

typedef GPB_ENUM(PhotonQuitRoom_FieldNumber) {
  PhotonQuitRoom_FieldNumber_Id_p = 1,
  PhotonQuitRoom_FieldNumber_RoomId = 2,
  PhotonQuitRoom_FieldNumber_Time = 3,
};

@interface PhotonQuitRoom : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;

@property(nonatomic, readwrite) int64_t time;

@end

#pragma mark - PhotonChannelMsg

typedef GPB_ENUM(PhotonChannelMsg_FieldNumber) {
  PhotonChannelMsg_FieldNumber_Raw = 1,
  PhotonChannelMsg_FieldNumber_Text = 2,
  PhotonChannelMsg_FieldNumber_Image = 3,
  PhotonChannelMsg_FieldNumber_Audio = 4,
  PhotonChannelMsg_FieldNumber_Video = 5,
  PhotonChannelMsg_FieldNumber_File = 6,
  PhotonChannelMsg_FieldNumber_Location = 7,
  PhotonChannelMsg_FieldNumber_RichText = 8,
  PhotonChannelMsg_FieldNumber_Id_p = 51,
  PhotonChannelMsg_FieldNumber_Time = 52,
  PhotonChannelMsg_FieldNumber_Fr = 53,
  PhotonChannelMsg_FieldNumber_To = 54,
  PhotonChannelMsg_FieldNumber_AtType = 55,
  PhotonChannelMsg_FieldNumber_AtListArray = 56,
  PhotonChannelMsg_FieldNumber_ReplyId = 57,
  PhotonChannelMsg_FieldNumber_ChannelId = 58,
  PhotonChannelMsg_FieldNumber_ReplyText = 59,
  PhotonChannelMsg_FieldNumber_IsReplace = 60,
  PhotonChannelMsg_FieldNumber_Extra = 100,
  PhotonChannelMsg_FieldNumber_InterExtra = 101,
};

typedef GPB_ENUM(PhotonChannelMsg_Data_OneOfCase) {
  PhotonChannelMsg_Data_OneOfCase_GPBUnsetOneOfCase = 0,
  PhotonChannelMsg_Data_OneOfCase_Raw = 1,
  PhotonChannelMsg_Data_OneOfCase_Text = 2,
  PhotonChannelMsg_Data_OneOfCase_Image = 3,
  PhotonChannelMsg_Data_OneOfCase_Audio = 4,
  PhotonChannelMsg_Data_OneOfCase_Video = 5,
  PhotonChannelMsg_Data_OneOfCase_File = 6,
  PhotonChannelMsg_Data_OneOfCase_Location = 7,
  PhotonChannelMsg_Data_OneOfCase_RichText = 8,
};

/**
 * [上下行]频道消息
 **/
@interface PhotonChannelMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fr;

/** 发消息的子频道ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite) PhotonChannelMsg_AtType atType;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *atListArray;
/** The number of items in @c atListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger atListArray_Count;

/** 回复的消息ID，默认为空 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *replyId;

/** 频道ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelId;

/** 回复的消息文本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *replyText;

/** 是否替换客户端原来的消息 */
@property(nonatomic, readwrite) BOOL isReplace;

@property(nonatomic, readonly) PhotonChannelMsg_Data_OneOfCase dataOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) PhotonRawMsgData *raw;

@property(nonatomic, readwrite, strong, null_resettable) PhotonTextMsgData *text;

@property(nonatomic, readwrite, strong, null_resettable) PhotonImageMsgData *image;

@property(nonatomic, readwrite, strong, null_resettable) PhotonAudioMsgData *audio;

@property(nonatomic, readwrite, strong, null_resettable) PhotonVideoMsgData *video;

@property(nonatomic, readwrite, strong, null_resettable) PhotonFileMsgData *file;

@property(nonatomic, readwrite, strong, null_resettable) PhotonLocationMsgData *location;

@property(nonatomic, readwrite, strong, null_resettable) PhotonRichTextMsgData *richText;

/** emoji => "[{}]" */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extra;
/** The number of items in @c extra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extra_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *interExtra;
/** The number of items in @c interExtra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger interExtra_Count;

@end

/**
 * Fetches the raw value of a @c PhotonChannelMsg's @c atType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PhotonChannelMsg_AtType_RawValue(PhotonChannelMsg *message);
/**
 * Sets the raw value of an @c PhotonChannelMsg's @c atType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPhotonChannelMsg_AtType_RawValue(PhotonChannelMsg *message, int32_t value);

/**
 * Clears whatever value was set for the oneof 'data'.
 **/
void PhotonChannelMsg_ClearDataOneOfCase(PhotonChannelMsg *message);

#pragma mark - PhotonDelCMsg

typedef GPB_ENUM(PhotonDelCMsg_FieldNumber) {
  PhotonDelCMsg_FieldNumber_Id_p = 1,
  PhotonDelCMsg_FieldNumber_Time = 2,
  PhotonDelCMsg_FieldNumber_To = 3,
  PhotonDelCMsg_FieldNumber_MsgIdsArray = 4,
  PhotonDelCMsg_FieldNumber_Extra = 100,
};

/**
 * [上下行]删除频道消息
 **/
@interface PhotonDelCMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t time;

/** 子频道ID，对应 ChannelMsg 里的 to 的值 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *msgIdsArray;
/** The number of items in @c msgIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgIdsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extra;
/** The number of items in @c extra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extra_Count;

@end

#pragma mark - PhotonRecallCMsg

typedef GPB_ENUM(PhotonRecallCMsg_FieldNumber) {
  PhotonRecallCMsg_FieldNumber_Id_p = 1,
  PhotonRecallCMsg_FieldNumber_Time = 2,
  PhotonRecallCMsg_FieldNumber_Fr = 3,
  PhotonRecallCMsg_FieldNumber_To = 4,
  PhotonRecallCMsg_FieldNumber_MsgId = 5,
  PhotonRecallCMsg_FieldNumber_Notice = 6,
  PhotonRecallCMsg_FieldNumber_DataType = 7,
  PhotonRecallCMsg_FieldNumber_OriginMsgTime = 8,
  PhotonRecallCMsg_FieldNumber_Extra = 100,
};

/**
 * [上下行]撤回频道消息
 **/
@interface PhotonRecallCMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

/** 上行非必输 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *notice;

@property(nonatomic, readwrite) int32_t dataType;

@property(nonatomic, readwrite) int64_t originMsgTime;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extra;
/** The number of items in @c extra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extra_Count;

@end

#pragma mark - PhotonSyncCMsg

typedef GPB_ENUM(PhotonSyncCMsg_FieldNumber) {
  PhotonSyncCMsg_FieldNumber_Clvs = 1,
};

/**
 * sync 频道消息 这个目前已经没有用了
 **/
@interface PhotonSyncCMsg : GPBMessage

/** 非必输, <子频道ID，游标> */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *clvs;
/** The number of items in @c clvs without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger clvs_Count;

@end

#pragma mark - PhotonSyncCHistory

typedef GPB_ENUM(PhotonSyncCHistory_FieldNumber) {
  PhotonSyncCHistory_FieldNumber_Clvs = 1,
  PhotonSyncCHistory_FieldNumber_To = 2,
  PhotonSyncCHistory_FieldNumber_LastKey = 3,
  PhotonSyncCHistory_FieldNumber_LastLv = 4,
  PhotonSyncCHistory_FieldNumber_LastTime = 5,
  PhotonSyncCHistory_FieldNumber_Direction = 6,
  PhotonSyncCHistory_FieldNumber_Count = 7,
  PhotonSyncCHistory_FieldNumber_Id_p = 10,
};

@interface PhotonSyncCHistory : GPBMessage

/** 非必输，格式：{子频道ID: 客户端保存的最大的游标，没有的话传0} */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *clvs;
/** The number of items in @c clvs without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger clvs_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

/** ChannelMsg extra 里下发的 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *lastKey;

/** 拉取两条艾特消息中间的消息时使用，传本地最小的那个lv，lastKey 传要拉取的那条艾特的lastKey */
@property(nonatomic, readwrite) int64_t lastLv;

/** 非必输 */
@property(nonatomic, readwrite) int64_t lastTime;

/** -1 拉取指定 lastKey 以前的消息，1 拉取指定lastKey 往后的消息 */
@property(nonatomic, readwrite) int32_t direction;

/** 客户端可以控制每次拉多少条消息 */
@property(nonatomic, readwrite) int32_t count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

#pragma mark - PhotonReadCMsg

typedef GPB_ENUM(PhotonReadCMsg_FieldNumber) {
  PhotonReadCMsg_FieldNumber_Id_p = 1,
  PhotonReadCMsg_FieldNumber_Time = 2,
  PhotonReadCMsg_FieldNumber_Fr = 3,
  PhotonReadCMsg_FieldNumber_To = 4,
  PhotonReadCMsg_FieldNumber_Cursor = 5,
};

/**
 * 消息已读的通知
 **/
@interface PhotonReadCMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

/** 最后一条消息的lv值 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cursor;

@end

#pragma mark - PhotonReplyCEmoji

typedef GPB_ENUM(PhotonReplyCEmoji_FieldNumber) {
  PhotonReplyCEmoji_FieldNumber_Id_p = 1,
  PhotonReplyCEmoji_FieldNumber_Time = 2,
  PhotonReplyCEmoji_FieldNumber_To = 3,
  PhotonReplyCEmoji_FieldNumber_EmojiId = 4,
  PhotonReplyCEmoji_FieldNumber_ReplyId = 5,
  PhotonReplyCEmoji_FieldNumber_ReplyLv = 6,
  PhotonReplyCEmoji_FieldNumber_Fr = 7,
  PhotonReplyCEmoji_FieldNumber_Action = 8,
  PhotonReplyCEmoji_FieldNumber_Extra = 10,
};

/**
 * channel回复表情的消息
 **/
@interface PhotonReplyCEmoji : GPBMessage

/** 当前消息的ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t time;

/** 子频道ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

/** 表情ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *emojiId;

/** 被回复的消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *replyId;

/** 被回复的消息的lv */
@property(nonatomic, readwrite) int64_t replyLv;

/** 当前用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fr;

/** 1 是回复，2 取消回复 */
@property(nonatomic, readwrite) int32_t action;

/** key 为 protocol_type 值为 set */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extra;
/** The number of items in @c extra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extra_Count;

@end

#pragma mark - PhotonRoomMsg

typedef GPB_ENUM(PhotonRoomMsg_FieldNumber) {
  PhotonRoomMsg_FieldNumber_Raw = 1,
  PhotonRoomMsg_FieldNumber_Text = 2,
  PhotonRoomMsg_FieldNumber_Image = 3,
  PhotonRoomMsg_FieldNumber_Audio = 4,
  PhotonRoomMsg_FieldNumber_Video = 5,
  PhotonRoomMsg_FieldNumber_File = 6,
  PhotonRoomMsg_FieldNumber_Location = 7,
  PhotonRoomMsg_FieldNumber_Id_p = 51,
  PhotonRoomMsg_FieldNumber_Time = 52,
  PhotonRoomMsg_FieldNumber_Fr = 53,
  PhotonRoomMsg_FieldNumber_To = 54,
  PhotonRoomMsg_FieldNumber_Extra = 100,
  PhotonRoomMsg_FieldNumber_InterExtra = 101,
};

typedef GPB_ENUM(PhotonRoomMsg_Data_OneOfCase) {
  PhotonRoomMsg_Data_OneOfCase_GPBUnsetOneOfCase = 0,
  PhotonRoomMsg_Data_OneOfCase_Raw = 1,
  PhotonRoomMsg_Data_OneOfCase_Text = 2,
  PhotonRoomMsg_Data_OneOfCase_Image = 3,
  PhotonRoomMsg_Data_OneOfCase_Audio = 4,
  PhotonRoomMsg_Data_OneOfCase_Video = 5,
  PhotonRoomMsg_Data_OneOfCase_File = 6,
  PhotonRoomMsg_Data_OneOfCase_Location = 7,
};

/**
 * [上下行]聊天室消息
 **/
@interface PhotonRoomMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readonly) PhotonRoomMsg_Data_OneOfCase dataOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) PhotonRawMsgData *raw;

@property(nonatomic, readwrite, strong, null_resettable) PhotonTextMsgData *text;

@property(nonatomic, readwrite, strong, null_resettable) PhotonImageMsgData *image;

@property(nonatomic, readwrite, strong, null_resettable) PhotonAudioMsgData *audio;

@property(nonatomic, readwrite, strong, null_resettable) PhotonVideoMsgData *video;

@property(nonatomic, readwrite, strong, null_resettable) PhotonFileMsgData *file;

@property(nonatomic, readwrite, strong, null_resettable) PhotonLocationMsgData *location;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extra;
/** The number of items in @c extra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extra_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *interExtra;
/** The number of items in @c interExtra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger interExtra_Count;

@end

/**
 * Clears whatever value was set for the oneof 'data'.
 **/
void PhotonRoomMsg_ClearDataOneOfCase(PhotonRoomMsg *message);

#pragma mark - PhotonMsg

typedef GPB_ENUM(PhotonMsg_FieldNumber) {
  PhotonMsg_FieldNumber_Raw = 1,
  PhotonMsg_FieldNumber_Text = 2,
  PhotonMsg_FieldNumber_Image = 3,
  PhotonMsg_FieldNumber_Audio = 4,
  PhotonMsg_FieldNumber_Video = 5,
  PhotonMsg_FieldNumber_File = 6,
  PhotonMsg_FieldNumber_Location = 7,
  PhotonMsg_FieldNumber_Id_p = 51,
  PhotonMsg_FieldNumber_Time = 52,
  PhotonMsg_FieldNumber_Fr = 53,
  PhotonMsg_FieldNumber_To = 54,
  PhotonMsg_FieldNumber_Extra = 100,
  PhotonMsg_FieldNumber_InterExtra = 101,
};

typedef GPB_ENUM(PhotonMsg_Data_OneOfCase) {
  PhotonMsg_Data_OneOfCase_GPBUnsetOneOfCase = 0,
  PhotonMsg_Data_OneOfCase_Raw = 1,
  PhotonMsg_Data_OneOfCase_Text = 2,
  PhotonMsg_Data_OneOfCase_Image = 3,
  PhotonMsg_Data_OneOfCase_Audio = 4,
  PhotonMsg_Data_OneOfCase_Video = 5,
  PhotonMsg_Data_OneOfCase_File = 6,
  PhotonMsg_Data_OneOfCase_Location = 7,
};

/**
 * [上下行]二人消息
 **/
@interface PhotonMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readonly) PhotonMsg_Data_OneOfCase dataOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) PhotonRawMsgData *raw;

@property(nonatomic, readwrite, strong, null_resettable) PhotonTextMsgData *text;

@property(nonatomic, readwrite, strong, null_resettable) PhotonImageMsgData *image;

@property(nonatomic, readwrite, strong, null_resettable) PhotonAudioMsgData *audio;

@property(nonatomic, readwrite, strong, null_resettable) PhotonVideoMsgData *video;

@property(nonatomic, readwrite, strong, null_resettable) PhotonFileMsgData *file;

@property(nonatomic, readwrite, strong, null_resettable) PhotonLocationMsgData *location;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extra;
/** The number of items in @c extra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extra_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *interExtra;
/** The number of items in @c interExtra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger interExtra_Count;

@end

/**
 * Clears whatever value was set for the oneof 'data'.
 **/
void PhotonMsg_ClearDataOneOfCase(PhotonMsg *message);

#pragma mark - PhotonGMsg

typedef GPB_ENUM(PhotonGMsg_FieldNumber) {
  PhotonGMsg_FieldNumber_Raw = 1,
  PhotonGMsg_FieldNumber_Text = 2,
  PhotonGMsg_FieldNumber_Image = 3,
  PhotonGMsg_FieldNumber_Audio = 4,
  PhotonGMsg_FieldNumber_Video = 5,
  PhotonGMsg_FieldNumber_File = 6,
  PhotonGMsg_FieldNumber_Location = 7,
  PhotonGMsg_FieldNumber_Id_p = 51,
  PhotonGMsg_FieldNumber_Time = 52,
  PhotonGMsg_FieldNumber_Fr = 53,
  PhotonGMsg_FieldNumber_To = 54,
  PhotonGMsg_FieldNumber_AtType = 55,
  PhotonGMsg_FieldNumber_AtListArray = 56,
  PhotonGMsg_FieldNumber_Extra = 100,
  PhotonGMsg_FieldNumber_InterExtra = 101,
};

typedef GPB_ENUM(PhotonGMsg_Data_OneOfCase) {
  PhotonGMsg_Data_OneOfCase_GPBUnsetOneOfCase = 0,
  PhotonGMsg_Data_OneOfCase_Raw = 1,
  PhotonGMsg_Data_OneOfCase_Text = 2,
  PhotonGMsg_Data_OneOfCase_Image = 3,
  PhotonGMsg_Data_OneOfCase_Audio = 4,
  PhotonGMsg_Data_OneOfCase_Video = 5,
  PhotonGMsg_Data_OneOfCase_File = 6,
  PhotonGMsg_Data_OneOfCase_Location = 7,
};

/**
 * [上下行]群消息
 **/
@interface PhotonGMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fr;

/** gid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite) PhotonGMsg_AtType atType;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *atListArray;
/** The number of items in @c atListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger atListArray_Count;

@property(nonatomic, readonly) PhotonGMsg_Data_OneOfCase dataOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) PhotonRawMsgData *raw;

@property(nonatomic, readwrite, strong, null_resettable) PhotonTextMsgData *text;

@property(nonatomic, readwrite, strong, null_resettable) PhotonImageMsgData *image;

@property(nonatomic, readwrite, strong, null_resettable) PhotonAudioMsgData *audio;

@property(nonatomic, readwrite, strong, null_resettable) PhotonVideoMsgData *video;

@property(nonatomic, readwrite, strong, null_resettable) PhotonFileMsgData *file;

@property(nonatomic, readwrite, strong, null_resettable) PhotonLocationMsgData *location;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extra;
/** The number of items in @c extra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extra_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *interExtra;
/** The number of items in @c interExtra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger interExtra_Count;

@end

/**
 * Fetches the raw value of a @c PhotonGMsg's @c atType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PhotonGMsg_AtType_RawValue(PhotonGMsg *message);
/**
 * Sets the raw value of an @c PhotonGMsg's @c atType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPhotonGMsg_AtType_RawValue(PhotonGMsg *message, int32_t value);

/**
 * Clears whatever value was set for the oneof 'data'.
 **/
void PhotonGMsg_ClearDataOneOfCase(PhotonGMsg *message);

#pragma mark - PhotonRawMsgData

typedef GPB_ENUM(PhotonRawMsgData_FieldNumber) {
  PhotonRawMsgData_FieldNumber_Arg1 = 1,
  PhotonRawMsgData_FieldNumber_Arg2 = 2,
  PhotonRawMsgData_FieldNumber_Data_p = 3,
  PhotonRawMsgData_FieldNumber_Size = 4,
};

/**
 * 自定义消息体数据
 **/
@interface PhotonRawMsgData : GPBMessage

/** 自定义int参数1，可作为消息类型或数据类型等用途 */
@property(nonatomic, readwrite) int32_t arg1;

/** 自定义int参数2，可作为消息类型或数据类型等用途 */
@property(nonatomic, readwrite) int32_t arg2;

/** 自定义二进制数据 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

/** 自定义二进制数据字节长度 */
@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - PhotonTextMsgData

typedef GPB_ENUM(PhotonTextMsgData_FieldNumber) {
  PhotonTextMsgData_FieldNumber_Text = 1,
};

/**
 * 文本消息数据
 **/
@interface PhotonTextMsgData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@end

#pragma mark - PhotonImageMsgData

typedef GPB_ENUM(PhotonImageMsgData_FieldNumber) {
  PhotonImageMsgData_FieldNumber_URL = 1,
  PhotonImageMsgData_FieldNumber_ThumbURL = 2,
  PhotonImageMsgData_FieldNumber_WhRatio = 3,
  PhotonImageMsgData_FieldNumber_Size = 4,
  PhotonImageMsgData_FieldNumber_BigURL = 5,
  PhotonImageMsgData_FieldNumber_HashAlg = 6,
  PhotonImageMsgData_FieldNumber_Hash_p = 7,
};

/**
 * 图片消息数据
 **/
@interface PhotonImageMsgData : GPBMessage

/** 原图url，必传 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

/** 缩略图url，会从from透传到to，非必传 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbURL;

@property(nonatomic, readwrite) float whRatio;

/** 文件大小，单位byte */
@property(nonatomic, readwrite) int64_t size;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bigURL;

/** hash算法 */
@property(nonatomic, readwrite) PhotonHashAlg hashAlg;

/** 文件hash值 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *hash_p;

@end

/**
 * Fetches the raw value of a @c PhotonImageMsgData's @c hashAlg property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PhotonImageMsgData_HashAlg_RawValue(PhotonImageMsgData *message);
/**
 * Sets the raw value of an @c PhotonImageMsgData's @c hashAlg property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPhotonImageMsgData_HashAlg_RawValue(PhotonImageMsgData *message, int32_t value);

#pragma mark - PhotonRichTextMsgData

typedef GPB_ENUM(PhotonRichTextMsgData_FieldNumber) {
  PhotonRichTextMsgData_FieldNumber_Text = 1,
  PhotonRichTextMsgData_FieldNumber_ImagesArray = 2,
};

/**
 * 包含文本和图片的消息
 **/
@interface PhotonRichTextMsgData : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PhotonTextMsgData *text;
/** Test to see if @c text has been set. */
@property(nonatomic, readwrite) BOOL hasText;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PhotonImageMsgData*> *imagesArray;
/** The number of items in @c imagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger imagesArray_Count;

@end

#pragma mark - PhotonAudioMsgData

typedef GPB_ENUM(PhotonAudioMsgData_FieldNumber) {
  PhotonAudioMsgData_FieldNumber_URL = 1,
  PhotonAudioMsgData_FieldNumber_AudioTime = 2,
  PhotonAudioMsgData_FieldNumber_Size = 3,
  PhotonAudioMsgData_FieldNumber_HashAlg = 4,
  PhotonAudioMsgData_FieldNumber_Hash_p = 5,
};

/**
 * 语音消息数据
 **/
@interface PhotonAudioMsgData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite) int64_t audioTime;

/** 文件大小，单位byte */
@property(nonatomic, readwrite) int64_t size;

/** hash算法 */
@property(nonatomic, readwrite) PhotonHashAlg hashAlg;

/** 文件hash值 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *hash_p;

@end

/**
 * Fetches the raw value of a @c PhotonAudioMsgData's @c hashAlg property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PhotonAudioMsgData_HashAlg_RawValue(PhotonAudioMsgData *message);
/**
 * Sets the raw value of an @c PhotonAudioMsgData's @c hashAlg property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPhotonAudioMsgData_HashAlg_RawValue(PhotonAudioMsgData *message, int32_t value);

#pragma mark - PhotonVideoMsgData

typedef GPB_ENUM(PhotonVideoMsgData_FieldNumber) {
  PhotonVideoMsgData_FieldNumber_URL = 1,
  PhotonVideoMsgData_FieldNumber_VideoTime = 2,
  PhotonVideoMsgData_FieldNumber_WhRatio = 3,
  PhotonVideoMsgData_FieldNumber_CoverURL = 4,
  PhotonVideoMsgData_FieldNumber_Size = 5,
  PhotonVideoMsgData_FieldNumber_HashAlg = 6,
  PhotonVideoMsgData_FieldNumber_Hash_p = 7,
};

/**
 * 视频消息数据
 **/
@interface PhotonVideoMsgData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite) int64_t videoTime;

@property(nonatomic, readwrite) float whRatio;

/** 视频的封面图，从from透传到to,非必传 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *coverURL;

/** 文件大小，单位byte */
@property(nonatomic, readwrite) int64_t size;

/** TODO 增加视频必要信息 */
@property(nonatomic, readwrite) PhotonHashAlg hashAlg;

/** 文件hash值 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *hash_p;

@end

/**
 * Fetches the raw value of a @c PhotonVideoMsgData's @c hashAlg property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PhotonVideoMsgData_HashAlg_RawValue(PhotonVideoMsgData *message);
/**
 * Sets the raw value of an @c PhotonVideoMsgData's @c hashAlg property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPhotonVideoMsgData_HashAlg_RawValue(PhotonVideoMsgData *message, int32_t value);

#pragma mark - PhotonLocationMsgData

typedef GPB_ENUM(PhotonLocationMsgData_FieldNumber) {
  PhotonLocationMsgData_FieldNumber_CoordinateSystem = 1,
  PhotonLocationMsgData_FieldNumber_Lng = 2,
  PhotonLocationMsgData_FieldNumber_Lat = 3,
  PhotonLocationMsgData_FieldNumber_Address = 4,
  PhotonLocationMsgData_FieldNumber_DetailedAddress = 5,
};

/**
 * 地理位置消息数据
 **/
@interface PhotonLocationMsgData : GPBMessage

/** 坐标系 */
@property(nonatomic, readwrite) PhotonCoordinateSystem coordinateSystem;

/** 经度 */
@property(nonatomic, readwrite) double lng;

/** 纬度 */
@property(nonatomic, readwrite) double lat;

/** 坐标地址名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

/** 坐标详细地址名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *detailedAddress;

@end

/**
 * Fetches the raw value of a @c PhotonLocationMsgData's @c coordinateSystem property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PhotonLocationMsgData_CoordinateSystem_RawValue(PhotonLocationMsgData *message);
/**
 * Sets the raw value of an @c PhotonLocationMsgData's @c coordinateSystem property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPhotonLocationMsgData_CoordinateSystem_RawValue(PhotonLocationMsgData *message, int32_t value);

#pragma mark - PhotonFileMsgData

typedef GPB_ENUM(PhotonFileMsgData_FieldNumber) {
  PhotonFileMsgData_FieldNumber_Name = 1,
  PhotonFileMsgData_FieldNumber_Size = 2,
  PhotonFileMsgData_FieldNumber_HashAlg = 3,
  PhotonFileMsgData_FieldNumber_Hash_p = 4,
  PhotonFileMsgData_FieldNumber_URL = 5,
};

/**
 * 文件消息数据
 **/
@interface PhotonFileMsgData : GPBMessage

/** 文件名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 文件大小，单位byte */
@property(nonatomic, readwrite) int64_t size;

/** hash算法 */
@property(nonatomic, readwrite) PhotonHashAlg hashAlg;

/** 文件hash值 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *hash_p;

/** 下载文件路径 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@end

/**
 * Fetches the raw value of a @c PhotonFileMsgData's @c hashAlg property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PhotonFileMsgData_HashAlg_RawValue(PhotonFileMsgData *message);
/**
 * Sets the raw value of an @c PhotonFileMsgData's @c hashAlg property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPhotonFileMsgData_HashAlg_RawValue(PhotonFileMsgData *message, int32_t value);

#pragma mark - PhotonDelMsg

typedef GPB_ENUM(PhotonDelMsg_FieldNumber) {
  PhotonDelMsg_FieldNumber_Id_p = 1,
  PhotonDelMsg_FieldNumber_Time = 2,
  PhotonDelMsg_FieldNumber_Fr = 3,
  PhotonDelMsg_FieldNumber_To = 4,
  PhotonDelMsg_FieldNumber_MsgIdsArray = 5,
};

@interface PhotonDelMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *msgIdsArray;
/** The number of items in @c msgIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgIdsArray_Count;

@end

#pragma mark - PhotonDelGMsg

typedef GPB_ENUM(PhotonDelGMsg_FieldNumber) {
  PhotonDelGMsg_FieldNumber_Id_p = 1,
  PhotonDelGMsg_FieldNumber_Time = 2,
  PhotonDelGMsg_FieldNumber_GroupId = 3,
  PhotonDelGMsg_FieldNumber_MsgIdsArray = 4,
};

@interface PhotonDelGMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *msgIdsArray;
/** The number of items in @c msgIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgIdsArray_Count;

@end

#pragma mark - PhotonRecallMsg

typedef GPB_ENUM(PhotonRecallMsg_FieldNumber) {
  PhotonRecallMsg_FieldNumber_Id_p = 1,
  PhotonRecallMsg_FieldNumber_Time = 2,
  PhotonRecallMsg_FieldNumber_Fr = 3,
  PhotonRecallMsg_FieldNumber_To = 4,
  PhotonRecallMsg_FieldNumber_MsgId = 5,
  PhotonRecallMsg_FieldNumber_Notice = 6,
  PhotonRecallMsg_FieldNumber_DataType = 7,
  PhotonRecallMsg_FieldNumber_OriginMsgTime = 8,
};

/**
 * [上下行]撤回二人消息
 **/
@interface PhotonRecallMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

/** 上行非必输 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *notice;

@property(nonatomic, readwrite) int32_t dataType;

@property(nonatomic, readwrite) int64_t originMsgTime;

@end

#pragma mark - PhotonRecallGMsg

typedef GPB_ENUM(PhotonRecallGMsg_FieldNumber) {
  PhotonRecallGMsg_FieldNumber_Id_p = 1,
  PhotonRecallGMsg_FieldNumber_Time = 2,
  PhotonRecallGMsg_FieldNumber_Fr = 3,
  PhotonRecallGMsg_FieldNumber_To = 4,
  PhotonRecallGMsg_FieldNumber_MsgId = 5,
  PhotonRecallGMsg_FieldNumber_Notice = 6,
  PhotonRecallGMsg_FieldNumber_DataType = 7,
  PhotonRecallGMsg_FieldNumber_OriginMsgTime = 8,
};

/**
 * [上下行]撤回群消息
 **/
@interface PhotonRecallGMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

/** 上行非必输 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *notice;

@property(nonatomic, readwrite) int32_t dataType;

@property(nonatomic, readwrite) int64_t originMsgTime;

@end

#pragma mark - PhotonMsgRead

typedef GPB_ENUM(PhotonMsgRead_FieldNumber) {
  PhotonMsgRead_FieldNumber_Id_p = 1,
  PhotonMsgRead_FieldNumber_Time = 2,
  PhotonMsgRead_FieldNumber_Fr = 3,
  PhotonMsgRead_FieldNumber_To = 4,
  PhotonMsgRead_FieldNumber_MsgIdsArray = 5,
  PhotonMsgRead_FieldNumber_DataTypeArray = 6,
};

/**
 * [上下行]二人消息已读
 **/
@interface PhotonMsgRead : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *msgIdsArray;
/** The number of items in @c msgIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgIdsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *dataTypeArray;
/** The number of items in @c dataTypeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger dataTypeArray_Count;

@end

#pragma mark - PhotonBadge

typedef GPB_ENUM(PhotonBadge_FieldNumber) {
  PhotonBadge_FieldNumber_CurrentBadge = 1,
};

/**
 * [上行]设置角标
 **/
@interface PhotonBadge : GPBMessage

@property(nonatomic, readwrite) int32_t currentBadge;

@end

#pragma mark - PhotonDebugLogUpload

typedef GPB_ENUM(PhotonDebugLogUpload_FieldNumber) {
  PhotonDebugLogUpload_FieldNumber_AllowMobileNet = 1,
  PhotonDebugLogUpload_FieldNumber_FileCountLimit = 2,
  PhotonDebugLogUpload_FieldNumber_ProcessesArray = 3,
};

/**
 * [下行]上传日志
 **/
@interface PhotonDebugLogUpload : GPBMessage

/** 是否允许非wifi网络上传日志 */
@property(nonatomic, readwrite) BOOL allowMobileNet;

/** 文件上传条数限制 */
@property(nonatomic, readwrite) int32_t fileCountLimit;

/** 进程 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *processesArray;
/** The number of items in @c processesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger processesArray_Count;

@end

#pragma mark - PhotonDebugLogClear

/**
 * [下行]清空本地日志文件
 **/
@interface PhotonDebugLogClear : GPBMessage

@end

#pragma mark - PhotonDebugLogTagAdd

typedef GPB_ENUM(PhotonDebugLogTagAdd_FieldNumber) {
  PhotonDebugLogTagAdd_FieldNumber_TagsArray = 1,
};

/**
 * [下行]添加日志过滤TAG
 **/
@interface PhotonDebugLogTagAdd : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tagsArray;
/** The number of items in @c tagsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tagsArray_Count;

@end

#pragma mark - PhotonDebugLogTagClear

/**
 * [下行]清空日志过滤TAG
 **/
@interface PhotonDebugLogTagClear : GPBMessage

@end

#pragma mark - PhotonDebugLogPrint

typedef GPB_ENUM(PhotonDebugLogPrint_FieldNumber) {
  PhotonDebugLogPrint_FieldNumber_Enable = 1,
};

/**
 * [下行]打开日志控制台输出
 **/
@interface PhotonDebugLogPrint : GPBMessage

@property(nonatomic, readwrite) BOOL enable;

@end

#pragma mark - PhotonDebugLogLevel

typedef GPB_ENUM(PhotonDebugLogLevel_FieldNumber) {
  PhotonDebugLogLevel_FieldNumber_Level = 1,
};

/**
 * [下行]设置日志等级
 **/
@interface PhotonDebugLogLevel : GPBMessage

@property(nonatomic, readwrite) int32_t level;

@end

#pragma mark - PhotonImTraceConfig

typedef GPB_ENUM(PhotonImTraceConfig_FieldNumber) {
  PhotonImTraceConfig_FieldNumber_Enable = 1,
  PhotonImTraceConfig_FieldNumber_ReportInterval = 2,
};

/**
 * [下行]im trace配置
 **/
@interface PhotonImTraceConfig : GPBMessage

/** 开关 */
@property(nonatomic, readwrite) BOOL enable;

/** 上报周期, 单位:秒 */
@property(nonatomic, readwrite) int32_t reportInterval;

@end

#pragma mark - PhotonRealtimeReport

@interface PhotonRealtimeReport : GPBMessage

@end

#pragma mark - PhotonPeriodicReport

typedef GPB_ENUM(PhotonPeriodicReport_FieldNumber) {
  PhotonPeriodicReport_FieldNumber_Period = 1,
};

@interface PhotonPeriodicReport : GPBMessage

@property(nonatomic, readwrite) int32_t period;

@end

#pragma mark - PhotonIndicatorFilter

typedef GPB_ENUM(PhotonIndicatorFilter_FieldNumber) {
  PhotonIndicatorFilter_FieldNumber_IndicatorsArray = 1,
};

@interface PhotonIndicatorFilter : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *indicatorsArray;
/** The number of items in @c indicatorsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger indicatorsArray_Count;

@end

#pragma mark - PhotonImStatLogConfig

typedef GPB_ENUM(PhotonImStatLogConfig_FieldNumber) {
  PhotonImStatLogConfig_FieldNumber_Enable = 1,
  PhotonImStatLogConfig_FieldNumber_IndicatorFilter = 2,
  PhotonImStatLogConfig_FieldNumber_RealtimeReport = 101,
  PhotonImStatLogConfig_FieldNumber_PeriodicReport = 102,
};

typedef GPB_ENUM(PhotonImStatLogConfig_ReportStrategy_OneOfCase) {
  PhotonImStatLogConfig_ReportStrategy_OneOfCase_GPBUnsetOneOfCase = 0,
  PhotonImStatLogConfig_ReportStrategy_OneOfCase_RealtimeReport = 101,
  PhotonImStatLogConfig_ReportStrategy_OneOfCase_PeriodicReport = 102,
};

@interface PhotonImStatLogConfig : GPBMessage

@property(nonatomic, readwrite) BOOL enable;

@property(nonatomic, readwrite, strong, null_resettable) PhotonIndicatorFilter *indicatorFilter;
/** Test to see if @c indicatorFilter has been set. */
@property(nonatomic, readwrite) BOOL hasIndicatorFilter;

@property(nonatomic, readonly) PhotonImStatLogConfig_ReportStrategy_OneOfCase reportStrategyOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) PhotonRealtimeReport *realtimeReport;

@property(nonatomic, readwrite, strong, null_resettable) PhotonPeriodicReport *periodicReport;

@end

/**
 * Clears whatever value was set for the oneof 'reportStrategy'.
 **/
void PhotonImStatLogConfig_ClearReportStrategyOneOfCase(PhotonImStatLogConfig *message);

#pragma mark - PhotonPingMsg

/**
 * 浏览器端使用
 **/
@interface PhotonPingMsg : GPBMessage

@end

#pragma mark - PhotonPongMsg

/**
 * 浏览器端使用
 **/
@interface PhotonPongMsg : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
